---
- name: Provision cluster resources
  openshift_provision:
    action: "{{ provision_action }}"
    patch_type: >-
      {{
      resource | json_query('metadata.annotations."openshift-provision/patch-type"')
      | default(resource.patch_type, true)
      | default('strategic', true)
      }}
    connection:
      oc_cmd: "{{ oc_cmd }}"
    resource: "{{ resource }}"
    generate_resources: "{{ generate_resources }}"
  with_items: "{{ resource_list }}"
  loop_control:
    loop_var: resource
    label:
      - Resource_kind - "{{ resource.kind }} ({{ resource.apiVersion }})"
      - Resource_name  - "{{ resource.metadata.name }}"
  vars:
    provision_action: >-
      {{
      resource | json_query('metadata.annotations."openshift-provision/action"')
      | default(resource.action, true)
      | default('apply', true)
      }}
  when: provision_action != 'ignore'
  register: provision
  changed_when: >-
    provision | record_change_provision(change_record)
  ignore_errors: True
- set_fact:
    provision_failures: "{{ provision_failures + provision.results }}"
  when: "'failed' in provision and 'results' in provision"
- set_fact:
    provision_failures_skipped: "{{ provision_failures_skipped + [provision] }}"
  when: "'results' not in provision"
