---
# Process openshift resources
- set_fact:
    provision_retry_limit: "{{ 0 if provision_retry_limit is undefined else provision_retry_limit }}"
    provision_retry_wait_seconds: "{{ 5 if provision_retry_wait_seconds is undefined else provision_retry_wait_seconds }}"
- name: Handle openshift_clusters
  include_tasks: openshift-cluster.yml
  with_items: >-
    {{ openshift_clusters
     | default([openshift_provision] if openshift_provision is defined else [])
    }}
  loop_control:
    loop_var: openshift_cluster
  vars:
    change_record: >-
      {{ openshift_cluster.change_record
       | default(openshift_provision_change_record)
      }}
    oc_cmd_opt: >-
      {{ oc_cmd_base }}
      {% if openshift_connection_certificate_authority is defined %}
      --certificate-authority={{ openshift_connection_certificate_authority | quote }}
      {% endif %}
      {% if openshift_connection_insecure_skip_tls_verify | default('false') | bool %}
      --insecure-skip-tls-verify
      {% endif %}
      {% if openshift_connection_server is defined %}
      --server={{ openshift_connection_server | quote }}
      {% endif %}
      {% if openshift_connection_token is defined %}
      --token={{ openshift_connection_token | quote }}
      {% endif %}
      {% if openshift_cluster.connection is defined %}
      {% for key, value in openshift_cluster.connection.items() %}
      --{{ key | regex_replace('_', '-') }}={{ value | quote }}
      {% endfor %}
      {% endif %}
  # openshift_host_env restricts play run to only process cluster on matching
  # environments, only run if openshift_host_env is not defined or matches.
  when: >-
    openshift_cluster.openshift_host_env is not defined or
    openshift_cluster.openshift_host_env == openshift_master_cluster_public_hostname or
    ( openshift_cluster.openshift_host_env | is_list and
      openshift_master_cluster_public_hostname in openshift_cluster.openshift_host_env
    )
