- name: Deprecation Warning
  fail:
    msg: USING DEPRECATED FEATURE openshift_clusters[*].projects[*].persistent_volume_claims
  ignore_errors: true

- name: Fail for missing persistent volume claim parameters
  fail: msg="This role requires persistent_volumes_claim.{{ item }} be set and non empty"
  when: persistent_volume_claim.{{ item }} is not defined or persistent_volume_claim.{{ item }} == ''
  with_items:
  - name
  - storage
  - access_modes

- name: Get persistent volume claim {{ persistent_volume_claim.name }} in project {{ project.name }}
  command: >
     {{ oc_cmd }} get pvc -n {{ project.name }} {{ persistent_volume_claim.name }} -o json
  register: get_pvc
  failed_when: false
  changed_when: false

- name: Create persistent volume claim {{ persistent_volume_claim.name }} in project {{ project.name }}
  when: get_pvc.rc != 0
  shell: >
    echo {{ ( pvc_def | combine(selector_def, recursive=True) if persistent_volume_claim.selector is defined else pvc_def ) | to_json | quote }}
    | {{ oc_cmd }} create -n {{ project.name }} -f -
  vars:
    pvc_def:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ persistent_volume_claim.name }}"
      spec:
        accessModes: "{{ persistent_volume_claim.access_modes }}"
        resources:
          requests:
            storage: "{% if persistent_volume_claim.storage | string | match('^[0-9]+$') %}{{ persistent_volume_claim.storage }}Gi{% else %}{{ persistent_volume_claim.storage }}{% endif %}"
    selector_def:
      spec:
        selector:
          matchLabels: "{{ persistent_volume_claim.selector | default({}) }}"
