---
- name: Get service accounts in {{ project.name }}
  command: >
    {{ oc_cmd }} get sa -n {{ project.name }} -o json
  check_mode: false
  changed_when: false
  failed_when: false
  register: get_service_accounts

- name: Create service accounts in {{ project.name }}
  command: >-
    {{ oc_cmd }} create serviceaccount {{ service_account_name }} -n {{ project.name }}
  with_items: "{{ project.service_accounts | default([]) }}"
  loop_control:
    loop_var: service_account
  vars:
    service_account_name: >-
      {% if service_account is mapping %}{{ service_account.name }}{% else %}{{ service_account }}{% endif %}
    service_account_query: "items[?metadata.name=='{{ service_account_name }}']|[0]"
    current_service_account: >-
      {{ get_service_accounts.stdout | from_json | json_query(service_account_query) }}
  when: >-
    current_service_account is undefined or
    current_service_account == ''
  register: command
  changed_when: >-
    command | record_change_command(change_record)
